# File: environment.yml
# File Created: Saturday, 9th February 2019 9:09:06 pm
# Author: Steven Atkinson (steven@atkinson.mn)

name: gptorch
channels:
  - pytorch
dependencies:
  - graphviz>=0.9
  - jupyter
  - matplotlib>=2.1.2
  - numpy>=1.10
  - pytest>=3.5.0
  - pytorch
  - scikit-learn>=0.19.1
  - scipy>=0.18
